### ISSUE TITLE
My upload image resolve is base64?

### ISSUE THREAD

**Issue by Yang-Jiaxiang** [nvt-ak/quill-upload#32]
I use asios post to my Api server,res is data.fileName.

But sometimes res is true(localhost:3090/image/${data.fileName}) ,false(<img class="quill-upload-progress" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAeAB4AAD/4RDyRXhpZgAATU0AKgAAAAgABAE7AAIAAAANAAAISodpAAQAAAABAA) why?

My stackoverflow https://stackoverflow.com/questions/71726432/react-quill-quill-upload-onupload-to-api-sometimes-notworking

![image](https://user-images.githubusercontent.com/81738019/161566905-6c347f5e-6a2c-409f-b734-baa47217622d.png)
![image](https://user-images.githubusercontent.com/81738019/161566852-dc5e5664-6bab-4b44-8ba1-d170c53738f0.png)

**Comment by nvt-ak** [comment]
fixed at version 0.0.10
