### ISSUE TITLE
Need JS version of library for every new release

### ISSUE THREAD

**Issue by rajaa-aamir98** [nvt-ak/quill-upload#54]
I need to change library from node.js to JS for every new release. Is it possible to get a JS version with each release?

**Comment by nvt-ak** [comment]
what exactly do you want?

**Comment by rajaa-aamir98** [comment]
We want the compiled version to simple js code as we need to integrate this functionality to our project. We have to follow the steps below every time we use the latest code: 
 
1- Download the zip file from the git hub, and unzip the folder
2- Install npm in system, go to the command prompt, and check version npm -v
3- Verify that your Unzipped folder has a webpack.config.js file and package.json file
4- Install Webpack and Webpack CLI using npm install webpack webpack-cli —save-dev
5- Install Clean Webpack Plugin npm install clean-webpack-plugin —save-dev
6- Install Html Webpack Plugin npm install html-webpack-plugin —save-dev
7- Install TerserPlugin npm install terser-webpack-plugin —save-dev Alternatively we can use the uglify plugin as well but the npm version must be compatible with that
8- Create or Modify Webpack Configuration if needed, remove uglify, add terser plugin configuration, and update the output file name

const path = require(“path”);
const { CleanWebpackPlugin } = require(“clean-webpack-plugin”);
const HtmlWebpackPlugin = require(“html-webpack-plugin”);
const TerserPlugin = require(“terser-webpack-plugin”);

module.exports = {
entry: {
workboard: “./src/index.js”,
},
output: {
filename: “add file name here.js”,
path: path.resolve(__dirname, “dist”), //this is the file path where we will save our generated file
},

code continues…
9- Update the package.json and add the webpack path in the scripts

{
  “scripts”: {
  “build”: “webpack path here”,
  “compile”: “npm run build”
  }
}
10- Finally compile the project npm run compile
